### ISSUE TITLE
Integer overflow in CglPreProcess.cpp

### ISSUE THREAD

**Issue by tosttost** [coin-or/Cgl#48]
CglPreProcess.cpp line 7779 can overflow. As xx.i is signed, this is undefined behaviour.

How to reproduce: 
Build Cbc with UBSAN and run the tests:
coinbrew build C --prefix="/build/dir" CFLAGS="-fsanitize=undefined -Wformat -Werror=format-security -Werror=array-bounds -g" CXXFLAGS="-fsanitize=undefined -Wformat -Werror=format-security -Werror=array-bounds -g" LDFLAGS="-fsanitize=undefined" --test

Note
* type punning using unions is undefined behaviour in C++ [1], so switching to an unsigned int does not fix this
  * type punning using unions is defined in C99
  * g++ supports it as an extension [2]
  * there are other places in the codebase that do type punning using unions.

[1] http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Ru-pun
[2] https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-fstrict-aliasing

**Comment by svigerske** [comment]
Interestingly it was already an `unsigned int` in the duplicate code in the `else` branch a few lines below.

This looks like a rather harmless warning, as it only matters that the behavior to get a hashvalue is deterministic.
