### ISSUE TITLE
Assertion in Reduce-and-split

### ISSUE THREAD

**Issue by christoph-cullmann** [coin-or/Cgl#58]
The attached ILP leads to an assertion:

`cbc value_45523.lp -cuts=off -gomory=forceLongOn -reduce=on -solve`

`### ERROR: CglRedSlpit::generateCuts(): rstat[41]: 0`

For that one, you need to specify the gomory cut option to trigger it, I have larger ones that get this even without other cuts.

[value_45523.lp.gz](https://github.com/coin-or/Cgl/files/5886207/value_45523.lp.gz)

Beside this assertions I get on some ILPs, the reduce yields very nice results reagarding problem solving runtime.

**Comment by christoph-cullmann** [comment]
Larger ilp:

`cbc value_375399.lp -reduce=on -solve`

`### ERROR: CglRedSlpit::generateCuts(): rstat[890]: 0`

Same issue with reduce2.

[value_375399.lp.gz](https://github.com/coin-or/Cgl/files/5886213/value_375399.lp.gz)

**Comment by jjhforrest** [comment]
Could not reproduce problem with smaller model - but can with this.

Seems fine to take out exit and just ignore free row - modified in master.

**Comment by christoph-cullmann** [comment]
Thanks a lot for the quick fix.

At least with my two small tests (as attached above) this works now nicely.

But I have ~200k more ILPs to try ;=)

Will follow up after they did run once.

**Comment by christoph-cullmann** [comment]
All Unix tests did pass here now, very nice, no new issues with this cut generator activated did show up and it really helps "a lot" for many problems.

The Windows stuff still differs because of issues like https://github.com/coin-or/Cgl/issues/57 but that is unrelated.

Thanks again for the quick fix!
