### ISSUE TITLE
AppVeyor jobs don't Test and conclude All successfull

### ISSUE THREAD

**Issue by jhmgoossens** [coin-or/Cgl#62]
Looking through the latest [Cgl build jobs logs on AppVeyor](https://ci.appveyor.com/project/coin-or/cgl), the tests don't actually seem to run anything. I looks like there are no solvers detected:

> Testing cut generators ...
> Sample directory: C:\projects\dist\share\coin-or-sample\
> Test directory: C:\projects\Cgl\test\CglTestData\
> Solvers:
> *****************************************
> All tests completed successfully

Earlier in the log, OsiClp is found
> checking for package OsiClp... yes

Is this expected behavior?

I noticed that CglConfig.h needs "CGLLIB_BUILD" defined in order to use the config with CGL_HAS_OSICLP 1, but could it be that CGLLIB_BUILD is not defined? I see "CGLUNITTEST_BUILD" instead.

**Comment by svigerske** [comment]
Good catch. We need to get some more defines from config.h, but defining `CGLLIB_BUILD` would break linking.
